version: "3.9"

services:
  flask:
    build: .
    ports:
      - 5001:5001
    volumes:
      - ./app/:/usr/app/
    restart: always

networks:
  default:
    external: true
    name: "imr-network"
